How to install and use git hooks
================================

= Hooks used in Ebank repo
Ebank repository uses following client-side hooks:

[[pre-push]]
Pre-push::
    Pre-push hook is used to ensure that code being published in repository is of good quality. For quality checks performed, see xref:qualitychecks[Quality checks] section. Due to performing extensive actions, push may take some time. +
    Pre-push hook uses Maven +static-analysis+ profile which adds tools configuration and executes tools (and generates reports) during +test+ phase. You may run +mvn -P static-analysis clean test+ manually to see if your code will pass quality checks before pushing it to repository (so you have a chance to fix issues).

TIP: To investigate why push didn't happen, use +git push+ command from terminal instead of using git client built into IDE. You may also try to find tools' reports (should be under +target/site+ directory).

[[qualitychecks]]
== Quality checks
Following quality checks are performed as part of the xref:pre-push[`pre-push`] hook.

. https://pmd.github.io/[pmd] static analysis to find common flaws such as unused variable, empty catch blocks,unnecessary object creation etc.
. https://github.com/spotbugs/spotbugs[spotbugs] static analysis to find bugs. Spotbugs exclusions are configured in +src/test/resources/static-analysis/spotbugs-exclude.xml+ filter file.
. https://www.jacoco.org/jacoco/[jacoco] for checking unit test code coverage - should be above 80% (this is the goal, you can set lower value by specifying +jacoco.instruction.minimum+ property, e.g. +mvn -P static-analysis clean test -Djacoco.instruction.minimum=0.65+). Threshold is also specified in +src/test/resources/static-analysis/static-analysis.properties+ file that is read by Maven during +git push+.

TIP: Good practice is to never decrease threshold. Once certain level of coverage is achieved, it should be maintained or increased when more tests are added.

= Hooks installation

To install the hooks, run appropriate scripts from *project's base directory* as described below. You _may_ need to make script executable first.

Hooks need to be installed manually on each developer's machine.

== Windows batch script

Pre-push::
    Run +git\scripts\pre-push-install.cmd+

== Linux shell (Git Bash)

Pre-push::
    Run +./git/scripts/pre-push-install.sh+
