openapi: 3.0.1
info:
  title: Swagger E-Banking
  description: >-
    This is E-banking server.
  termsOfService: "http://swagger.io/terms/"
  contact:
    email: lukasz.stefaniszyn@capgemini.com
  license:
    name: Apache 2.0
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
  version: 1.0.0
servers:
  - url: "{protocol}://10.40.234.149:{port}/api/v1"
    variables:
      protocol:
        enum:
          - 'http'
          - 'https'
        default: 'http'
      port:
        enum:
          - '8080'
          - '8443'
        default: '8080'
tags:
  - name: customer
    description: Operations about customer
  - name: account
    description: Operations about account
paths:
  "/api":
    get:
      tags:
        - app
      summary: Get API status
      operationId: getStatus
      responses:
        "200":
          description: successful operation
          content:
            application/json:
              schema:
                type: object
                items:
                  $ref: "#/components/schemas/AppStatus"
        "400":
          description: Error
          content: {}
        "404":
          description: Error
          content: {}
  "/customers":
    get:
      tags:
        - customer
      summary: Get all customers
      operationId: getcustomers
      responses:
        "200":
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Customer"
        "400":
          description: Invalid customer id supplied
          content: {}
        "404":
          description: customer not found
          content: {}
  "/customers/{id}":
    get:
      tags:
        - customer
      summary: Get customer by id
      operationId: getcustomerById
      parameters:
        - name: id
          in: path
          description: 'The id that needs to be fetched. Use "1" for testing. '
          required: true
          schema:
            type: string
      responses:
        "200":
          description: successful operation
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Customer"
        "400":
          description: Invalid customer id supplied
          content: {}
        "404":
          description: customer not found
          content: {}
  "/customers/{id}/accounts":
    get:
      tags:
        - account
      summary: Get customer's accounts
      operationId: getcustomerAccounts
      parameters:
        - name: id
          in: path
          description: 'The id that needs to be fetched. Use "1" for testing. '
          required: true
          schema:
            type: string
      responses:
        "200":
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Account"
        "400":
          description: Invalid customer id supplied
          content: {}
        "404":
          description: customer not found
          content: {}
  "/customers/{id}/accounts/{idAccount}/transactions":
    get:
      tags:
        - account
      summary: Get account's transactions
      operationId: getAccountTransactions
      parameters:
        - name: id
          in: path
          description: 'The id that needs to be fetched. Use "1" for testing. '
          required: true
          schema:
            type: string
        - name: idAccount
          in: path
          description: 'The idAccount that needs to be fetched. Use "1" for testing. '
          required: true
          schema:
            type: string
      responses:
        "200":
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Transaction"
        "400":
          description: Invalid customer id supplied
          content: {}
        "404":
          description: customer not found
          content: {}
  "/accounts/{idAccount}/transactions":
    get:
      security:
        - bearerAuth: []
      tags:
        - account
      summary: Get account's transactions secured
      operationId: getAccountTransactionsSecured
      parameters:
        - name: idAccount
          in: path
          description: 'The idAccount that needs to be fetched. Use "1" for testing. '
          required: true
          schema:
            type: string
      responses:
        "200":
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Transaction"
        "400":
          description: Invalid customer id supplied
          content: {}
        '401':
          $ref: '#/components/responses/UnauthorizedError'
        "404":
          description: customer not found
          content: {}
components:
  schemas:
    Currency:
      type: object
      properties:
        name:
          type: string
          description: like, Euro
        code:
          type: string
          description: like, EUR
      xml:
        name: Currency
    Account:
      type: object
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        currency:
          $ref: "#/components/schemas/Currency"
      xml:
        name: Account
    Customer:
      type: object
      properties:
        id:
          type: integer
          format: int64
        givenName:
          type: string
          description: https://schema.org/givenName
        familyName:
          type: string
          description: https://schema.org/familyName
        accounts:
          type: array
          xml:
            name: account
            wrapped: false
          items:
            $ref: "#/components/schemas/Account"
      xml:
        name: User
    AppStatus:
      type: object
      properties:
        app-version:
          type: string
          description: https://schema.org/version
      xml:
        name: AppStatus
    Transaction:
      type: object
      properties:
        id:
          type: integer
          format: int64
        value:
          type: object
          properties:
            amount:
              type: integer
              format: int64
            currency:
              $ref: "#/components/schemas/Currency"
        iban:
          type: string
        date:
          type: string
          format: date-time
        description:
          type: string
      xml:
        name: Transaction
    ApiResponse:
      type: object
      properties:
        code:
          type: integer
          format: int32
        type:
          type: string
        message:
          type: string
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  responses:
    UnauthorizedError:
      description: Access token is missing or invalid
      content: {}