version: '3.3'

services:

  db:
    image: postgres
    restart: always
    ports:
        - 5432:5432
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres

  swagger:
    image: swaggerapi/swagger-editor
    restart: always
    ports:
      - 80:8080