node{

    stage('Checkout code'){
        git branch: "${BRANCH_NAME}", url: 'https://github.com/lstefaniszyn/e-bank_.git', credentialsId: '6a24fa14-5cfa-4e86-916f-a4d58bd60add'
    }


    stage('Compile'){
        docker.image('maven:3.6.3-openjdk-11').inside{
            sh 'mvn compile'
        }
    }
    stage('Test'){
        docker.image('maven:3.6.3-openjdk-11').inside{
            sh 'mvn test'
        }
    }
    stage('Reports'){
        junit 'target/surefire-reports/*.xml'
        allure includeProperties: true, jdk: '', report: 'target/site/allure/report/unit', results: [[path: 'target/allure/results/unit']]
        jacoco classPattern: 'target/classes', exclusionPattern: '**/*Test*.class', execPattern: 'target/jacoco.exec', inclusionPattern: '**/*.class', sourcePattern: 'src/main/java'
        publishHTML([allowMissing: false, alwaysLinkToLastBuild: true, keepAll: true, reportDir: 'target/site/jacoco', reportFiles: 'index.html', reportName: 'Coverage Report', reportTitles: ''])
    }

    stage('Static analysis') {
        docker.image('rawdee/pmd:latest').inside('-v $PWD/src/main/java:/src'){
            sh(script: 'pmd -language java -dir . -rulesets rulesets/java/quickstart.xml -f html > pmd.html', returnStatus: true)
            // TODO: publishHTML report
        }
        // TODO: checkstyle
        // TODO: findbugs
    }
    stage('Security scan') {
        echo 'TODO: Security scan'
    }
    stage('Integration tests'){
        docker.image('maven:3.6.3-openjdk-11').inside{
            sh 'mvn -Dskip.surefire.tests=true verify'
        }
        junit 'target/failsafe-reports/*.xml'
        allure includeProperties: true, jdk: '', report: 'target/site/allure/report/combined', results [[path: 'target/allure/results/it'], [path: 'target/allure/results/unit']]
    }
    docker.image('maven:3.6.3-openjdk-11').inside{
        stage('Package'){
            sh 'mvn package -DskipTests=true'
        }
    }
    stage('Build docker image') {
        def dockerImageId = docker.build('ebank:latest', '-f ./docker/Dockerfile .')
    }
    stage('Push docker image') {
        echo 'TODO: Push docker'
    }
    stage('Remove docker image') {
        sh "docker image rm -f ${dockerImageId}"
    }
}
