package com.example.ebank.controllers;

import com.example.ebank.autogenerated.api.AccountApi;
import com.example.ebank.autogenerated.dto.AccountDto;
import com.example.ebank.autogenerated.dto.TransactionPageDto;
import com.example.ebank.mappers.AccountMapper;
import com.example.ebank.mappers.TransactionMapper;
import com.example.ebank.models.Account;
import com.example.ebank.models.Transaction;
import com.example.ebank.services.AccountService;
import com.example.ebank.services.CustomerService;
import com.example.ebank.services.TransactionService;
import com.example.ebank.utils.SecurityContextUtils;
import io.swagger.annotations.Api;
import org.springframework.data.domain.Page;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.RestController;

import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.time.format.DateTimeFormatterBuilder;
import java.time.temporal.ChronoField;
import java.util.List;


@RestController
public class AccountController extends BasicController implements AccountApi {

    private final static String DATE_FORMAT = "yyyy-MM";
    private final static DateTimeFormatter DATE_FORMATTER = new DateTimeFormatterBuilder()
            .append(DateTimeFormatter.ofPattern(DATE_FORMAT)).parseDefaulting(ChronoField.DAY_OF_MONTH, 1)
            .toFormatter();

    private final AccountService accountService;
    private final TransactionService transactionService;
    private final AccountMapper accountMapper;
    private final TransactionMapper transactionMapper;

    public AccountController(CustomerService customerService,
            AccountService accountService,
            AccountMapper accountMapper,
            TransactionService transactionService,
            TransactionMapper transactionMapper,
            SecurityContextUtils securityContextUtils) {
        super(customerService, securityContextUtils);
        this.accountService = accountService;
        this.accountMapper = accountMapper;
        this.transactionService = transactionService;
        this.transactionMapper = transactionMapper;
    }

    @Override
    public ResponseEntity<List<AccountDto>> getCustomerAccounts(Long customerId) {
        validateAccessToRequestedCustomer(customerId);
        return ResponseEntity.ok(accountMapper.toListDto(accountService.getAllForCustomer(customerId)));
    }

    @Override
    public ResponseEntity<AccountDto> getCustomerAccount(Long customerId, Long accountId) {
        validateAccessToRequestedCustomer(customerId);
        Account account = accountService.getOneForCustomer(accountId, customerId);
        return ResponseEntity.ok(accountMapper.toDto(account));
    }

    @Override
    public ResponseEntity<TransactionPageDto> getAccountTransactions(Long customerId, Long accountId, String dateString,
            Integer page, Integer size) {
        validateAccessToRequestedCustomer(customerId);
        Account account = accountService.getOneForCustomer(accountId, customerId);

        LocalDate date = LocalDate.parse(dateString, DATE_FORMATTER);

        Page<Transaction> resultPage = transactionService.findForAccountInMonthPaginated(account.getId(), date, page,
                size);
        return ResponseEntity.ok(transactionMapper.toTransactionPageDto(resultPage));
    }

}