package com.example.ebank.controllers;

import com.example.ebank.autogenerated.api.AppApi;
import com.example.ebank.autogenerated.dto.AppStatusDto;
import com.example.ebank.configuration.OpenApiProperties;

import io.swagger.annotations.Api;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.RestController;

@RestController
public class AppStatusController implements AppApi {

    @Value("${app.version}")
    private String appVersion;

    @Override
    public ResponseEntity<AppStatusDto> getStatus() {
        AppStatusDto dto = new AppStatusDto();
        dto.setAppVersion(appVersion);
        return ResponseEntity.ok(dto);
    }

}
